version: '3.8'

services:
    reverse-proxy:
        image: nginx:latest
        ports:
            - 80:80
        depends_on:
            - auth-service
        volumes:
            - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf

    auth-service:
        image: auth-service:1.0.0
        build:
            context: ./src/auth-service
        ports:
            - "50050:50050"
        expose:
            - 50050
        depends_on:
            - mongo
        environment:
            DATABASE_URL: mongodb://mongo:27017/maple_fighters
            
    character-service:
        image: character-service:1.0.0
        build:
            context: ./src/character-service
        ports:
            - "50053:50053"
        expose:
            - 50053
        depends_on:
            - postgres
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50053
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

    game-service:
        image: game-service:1.0.0
        build:
            context: ./src/game-service
        ports:
            - "50051:50051"
        expose:
            - 50051

    gameprovider-service:
        image: gameprovider-service:1.0.0
        build:
            context: ./src/gameprovider-service
        ports:
            - "50052:50052"
        expose:
            - 50052
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50052
            DATABASE_PATH: tmp/data.json

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    mongo:
        image: mongo
	    ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
