version: '3.8'

services:
    reverse-proxy:
        image: nginx:latest
        ports:
            - 80:80
        depends_on:
            - auth-service
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    auth-service:
        image: auth-service:1.0.0
        build:
            context: ./auth-service
        ports:
            - "50050:50050"
        expose:
            - 50050

    character-service:
        image: character-service:1.0.0
        build:
            context: ./character-service
        ports:
            - "50053:50053"
        depends_on:
            - postgres
        expose:
            - 50053
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50053
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

    game-service:
        image: game-service:1.0.0
        build:
            context: ./game-service
        ports:
            - "50051:50051"
        expose:
            - 50051

    gameprovider-service:
        image: gameprovider-service:1.0.0
        build:
            context: ./gameprovider-service
        ports:
            - "50052:50052"
        expose:
            - 50052
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50052
            DATABASE_PATH: tmp/data.json

    postgres:
        image: postgres:latest
        env_file: .env-postgres
        ports:
            - "5432:5432"